version: "3.4"

services:
    pgAdmin:
        restart: always
        image: dpage/pgadmin4
        ports:
            - "8000:80"
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@example.com
            PGADMIN_DEFAULT_PASSWORD: 1234
        volumes:
            - pgadmin:/var/lib/pgadmin
    postgres:
        restart: always
        image: postgres
        container_name: "postgres_container"
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 1234
            POSTGRES_DB: golang_crud
        volumes:
            - pgvol:/var/lib/postgresql/data
            - ./buku.sql:/docker-entrypoint-initdb.d/data.sql
volumes:
    pgvol:
    pgadmin: 